# Generated by Django 4.2.9 on 2025-08-27 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_code', models.CharField(max_length=20, unique=True, verbose_name='CV số')),
                ('title', models.CharField(max_length=255, verbose_name='Tên công việc')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='% hoàn thành')),
                ('status', models.CharField(choices=[('NEW', 'Chưa bắt đầu'), ('DOING', 'Đang thực hiện'), ('PENDING', 'Chờ phê duyệt'), ('DONE', 'Đã hoàn thành')], default='NEW', max_length=10, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phê duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Chỉ huy phê duyệt')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giao')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('supporters', models.ManyToManyField(blank=True, related_name='supporting_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Hỗ trợ')),
            ],
            options={
                'ordering': ['-approved_at', '-updated_at'],
                'permissions': [('can_approve', 'Có thể phê duyệt công việc')],
            },
        ),
    ]
