# Generated by Django 4.2.9 on 2025-08-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_task_content_alter_task_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cv_code',
        ),
    ]
