# Generated by Django 4.2.9 on 2025-08-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0006_taskupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='managerfeedback',
            name='note',
        ),
        migrations.RemoveField(
            model_name='taskupdate',
            name='note',
        ),
        migrations.AddField(
            model_name='managerfeedback',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung phản hồi'),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung cập nhật'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managerfeedbacks', to='work.task'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='% hoàn thành'),
        ),
    ]
