# Generated by Django 4.2.9 on 2025-08-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_managerfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerfeedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedbacks', to='work.task'),
        ),
    ]
