# Generated by Django 4.2.9 on 2025-08-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0008_alter_managerfeedback_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi quản lý', 'verbose_name_plural': 'Phản hồi quản lý'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve', 'Có thể phê duyệt công việc')], 'verbose_name': 'Công việc', 'verbose_name_plural': 'Công việc'},
        ),
        migrations.AlterModelOptions(
            name='taskupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cập nhật công việc', 'verbose_name_plural': 'Cập nhật công việc'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn hoàn thành'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giờ ước tính'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', '📌 Thấp'), ('MEDIUM', '📝 Trung bình'), ('HIGH', '🔥 Cao'), ('URGENT', '⚡ Khẩn cấp')], default='MEDIUM', max_length=10, verbose_name='Độ ưu tiên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Mã phòng ban'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='content',
            field=models.TextField(verbose_name='Nội dung phản hồi'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian phản hồi'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedbacks', to='work.task', verbose_name='Công việc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giao việc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', '🆕 Chưa bắt đầu'), ('DOING', '🚀 Đang thực hiện'), ('PENDING', '⏳ Chờ phê duyệt'), ('DONE', '✅ Đã hoàn thành'), ('CANCELLED', '❌ Đã hủy')], default='NEW', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supporting_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người hỗ trợ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='work.task', verbose_name='Công việc'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_updates', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
    ]
