# Generated by Django 4.2.9 on 2025-08-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve', 'Có thể phê duyệt công việc'), ('view_all_tasks', 'Có thể xem tất cả công việc (read-only)')], 'verbose_name': 'Công việc', 'verbose_name_plural': 'Công việc'},
        ),
    ]
