# Generated by Django 4.2.9 on 2025-09-03 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian phản hồi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Hạn hoàn thành'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', '📌 Thấp'), ('MEDIUM', '📝 Trung bình'), ('HIGH', '🔥 Cao'), ('URGENT', '⚡ Khẩn cấp')], db_index=True, default='MEDIUM', max_length=10, verbose_name='Độ ưu tiên'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% hoàn thành'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', '🆕 Chưa bắt đầu'), ('DOING', '🚀 Đang thực hiện'), ('PENDING', '⏳ Chờ phê duyệt'), ('DONE', '✅ Đã hoàn thành'), ('CANCELLED', '❌ Đã hủy')], db_index=True, default='NEW', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% hoàn thành'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='work_depart_is_acti_fc199b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='work_depart_name_22d23d_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='work_depart_code_66a27b_idx'),
        ),
        migrations.AddIndex(
            model_name='managerfeedback',
            index=models.Index(fields=['task', 'created_at'], name='work_manage_task_id_6b2dec_idx'),
        ),
        migrations.AddIndex(
            model_name='managerfeedback',
            index=models.Index(fields=['manager', 'created_at'], name='work_manage_manager_9e3193_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='work_task_status_c46bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='work_task_assigne_fa6022_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department', 'status'], name='work_task_departm_1e853e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline', 'status'], name='work_task_deadlin_99af18_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='work_task_created_78dd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['updated_at'], name='work_task_updated_a5ea59_idx'),
        ),
        migrations.AddIndex(
            model_name='taskupdate',
            index=models.Index(fields=['task', 'created_at'], name='work_taskup_task_id_6dc9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskupdate',
            index=models.Index(fields=['user', 'created_at'], name='work_taskup_user_id_f653e7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='work_userpr_user_id_31dbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department'], name='work_userpr_departm_7d8b47_idx'),
        ),
    ]
