# Generated by Django 4.2.9 on 2025-09-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_managerfeedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét khi duyệt'),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm duyệt (1–10)'),
        ),
    ]
